### PR TITLE
upgrade asap dep to 2.0.0

### PR DESCRIPTION
**Pull request by mvayngrib**
1.0.0 doesn't browserify well

### CODE REVIEW

**Comment by feross** [comment]
Out of curiosity, what about 1.0.0 doesn't browserify well?

**Comment by mvayngrib** [comment]
its exception handling thinks it's in node.js (see the isNodeJS var) and
rethrows synchronously, breaking its flush loop. This means that after an
exception is thrown, unless it is caught in a domain, it will never
recover. In my code, this meant no promise was ever resolved again

**Comment by feross** [comment]
I actually saw this happen once and couldn't figure out why. Thanks for
explaining.

+1 to this PR!

**Comment by mvayngrib** [comment]
ha, yea, I emerged from this one with my head well-scratched

**Comment by othiym23** [comment]
Sorry it took us a minute, but this has been rebased and landed as 0297176343bd69c2f7714f3752962f2f537c484c, as well as published as `dezalgo@1.0.3`. Thanks for putting this together, and best of luck with getting dezalgo to browserify properly!

**Comment by mvayngrib** [comment]
awesome, i'm off to dezalgo something

**Pull request closed without merging**
